server:
  port: 8084
  servlet:
    context-path: /shipping-server
spring:
  application:
    name: shipping-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.18.193.77:3306/shipping_db
    username: root
    password: dzm123%*
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  devtools:
    restart:
      enabled: true
      exclude: static/*

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka



