server:
  port: 8085
  servlet:
    context-path: /user-server

spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.18.193.77:3306/user_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: dzm123%*
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      exclude: static/*

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka